### PR TITLE
Corrections in Acquisition card task

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
- Fix in the task perfom method card for the "avg befre demod" operation for the sp card.
- Reduce code duplication.
- Add coherence checks for the "use as ref" option for channel 2.

Missing:
- [x] fix the conversion of traces in the sp card driver when no average is performed (float32 conversion)
- [x] make the alazar driver return 1D array when averaging before demod

### CODE REVIEW

**Comment by lcontami** [comment]
I am confused. Why do you want a 1D array ?
To me the expected output of the get_traces method is a list of n_channels x record_length traces when averaging.

(also I'm very confused about adding 2 zeros when the channel is not active but why not)

**Comment by MatthieuDartiailh** [comment]
I mean a 1D array per channel (sorry). The arrays filled with 0 is just to keep a constant output type.

**Comment by MatthieuDartiailh** [comment]
@lcontami you could change Smartgit setting to properly sign your own commit rather than attributing them to me.

**Comment by MatthieuDartiailh** [comment]
This is good to go as far as I am concerned.
@leghtas could you review the changes and make sure everything is ok with the Alazar ?
@lcontami did you check everything is fine with the AQD14 ?

**Comment by leghtas** [comment]
Looks good to me

**Comment by MatthieuDartiailh** [comment]
Thanks @leghtas. As soon as you can check that everything is fine with the SP @lcontami, feel free to merge (you can approve the pull request, I can't as I opened it).

**Comment by MatthieuDartiailh** [comment]
Alternatively @galactikvoyager if you run some measurements this week, could you check the sp card ?

**Comment by MatthieuDartiailh** [comment]
Should I assume that it now works properly and can be merged ?

**Comment by lcontami** [comment]
Yes!

**Comment by MatthieuDartiailh** [comment]
Ok so @lcontami, @leghtas, @galactikvoyager any of you has the authority to merge (and first approve the changes save if you feel like using your administrator privileges). When merging, please do a squash and merge to keep only one commit in the history.

**Comment by lcontami** [comment]
Additional question:
is there a place where the instrument drivers are tested ?
For the last error, the get_trace method for the SPADQ14 card was incorrect but this could have been easily tested.

**Pull request merged**
