### PR TITLE
instruments : add connection for DLL instruments

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@tcubaynes could you give a look at the last changes I made. I actually noticed that the card use signed integer at least this way the card and the oscilloscope agree. Perhaps you could check what is said in the docs about that.
Also I think we could improve a bit further the connection, but this could be addressed later.

**Comment by tcubaynes** [comment]
I have seen nothing in the doc about the type of integer: the function GetData is using or the internal RAM is containing. In the driver line 199, I think the "assert" should raise an error since the trigger is already disarmed at the end of get_traces ? Also, I didn't get the use of the loop line 212 "if not get_data...", but I will ask you again when I will be back.

**Comment by MatthieuDartiailh** [comment]
Need to merge https://github.com/Ecpy/ecpy_pulses/pull/7 before the tests can pass

**Comment by MatthieuDartiailh** [comment]
Good catch

**Pull request merged**
